# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('image', models.CharField(max_length=500)),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Places',
                'verbose_name': 'Place',
            },
        ),
    ]
